### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/www.rust-lang.org#185]
*content*
- [x] (formerly #165) "Rust in Production" is not like the other "action" titles. do we want to change it?
- [ ] (formerly #150) improve thematic statement to "The programming language that empowers everyone to be a systems programmer."
- [x] (formerly #150) add get started button that links to getting started page
- [x] (formerly #150) add language values section (#238)
- [x] (formerly #146) add ability to dynamically display version and release date of latest stable rust on install button
- [x] (formerly #42) install button goes to rustup page, not like the current site does. i think we want to preserve what the current website does? thought?

*design*

- [ ] polish pass for CSS
