### ISSUE TITLE
Tools Page

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/www.rust-lang.org#187]
**content**

- [x] (formerly issue #125) Consider dropping the prelude and postlude (first and last sections). I don't think they are adding a lot (what they say applies to most languages) and in general we've preferred punch, 2-3 sentence paragraphs connected with some specific image+sales pitch.
- [x] (formerly issue #125) The "init" section: not sure exactly what the intent here is
- [ ] (formerly issue #125) "Write": rather than listing editor integrations in pure text, seems better to show an array of logos + names (see "IDEs for Scala" here)
- [ ] (formerly issue #125) Figure out what we want to do for the tool "graphics" and links.
- [x] every section should have a call to action

**design**

- [x] page needs design attention to improve visual rhythm (alternating images)
- [ ] image sizes need to be handled

**links**

- local: http://localhost:7878/tools
- live: http://rust-wubwub.herokuapp.com/tools
