### ISSUE TITLE
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

### ISSUE THREAD

**Issue by 0338399145** [rust-lang/www.rust-lang.org#1872]
```[tasklist]
### Tasks
- [ ] https://github.com/rust-lang/www.rust-lang.org/pull/1865
- [ ] https://github.com/rust-lang/www.rust-lang.org/pull/1870
- [ ] https://github.com/rust-lang/www.rust-lang.org/issues/1866
- [ ] https://github.com/rust-lang/www.rust-lang.org/issues/1863
- [x] curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
