### ISSUE TITLE
winsoft

### ISSUE THREAD

**Issue by soft2i** [rust-lang/www.rust-lang.org#1931]
winsoft inobator sin nuves de umo
![Git-Logo-1788C](https://github.com/rust-lang/www.rust-lang.org/assets/159884685/85af54a4-8750-4ee3-b776-7415c52c8812)

```[tasklist]
### Tasks
- [ ] https://github.com/rust-lang/www.rust-lang.org/pull/1930
- [ ] https://github.com/rust-lang/www.rust-lang.org/issues/1926
- [ ] https://github.com/rust-lang/www.rust-lang.org/pull/1898
- [ ] https://github.com/rust-lang/www.rust-lang.org/issues/1927
- [ ] https://github.com/rust-lang/www.rust-lang.org/pull/1925
- [ ] https://github.com/rust-lang/www.rust-lang.org/issues/928
- [ ] https://github.com/rust-lang/www.rust-lang.org/issues/426
```
