### ISSUE TITLE
navigator.platform: Linux armv81 navigator.appVersion: 5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36

### ISSUE THREAD

**Issue by Ahlam6219977** [rust-lang/www.rust-lang.org#1958]
navigator.platform: Linux armv81
navigator.appVersion: 5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36
```[tasklist]
### Tasks
- [ ] https://github.com/rust-lang/www.rust-lang.org/pull/1898
- [ ] https://github.com/rust-lang/www.rust-lang.org/pull/1697
- [ ] https://github.com/rust-lang/www.rust-lang.org/issues/1956
```

**Comment by Ahlam6219977** [comment]
Re: [rust-lang/www.rust-lang.org] navigator.platform: Linux armv81 navigator.appVersion: 5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36 (Issue #1958)Re: [rust-lang/www.rust-lang.org] navigator.platform: Linux armv81 navigator.appVersion: 5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36 (Issue #1958)
