### ISSUE TITLE
Tools Page tracking issue

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/www.rust-lang.org#219]
*content*

- [ ] let's replace buttons with IDE icons. 

*design*

- [x] migrate to tachyons – not started
- [x] responsive styling pass
- [ ] include icons
- [x] fold all jetbrains products into "jetbrains" - https://github.com/rust-lang/wubwub/pull/207#discussion_r234353166)

**Comment by skade** [comment]
Outstanding issues:

* [ ] "It looks like you're writing an Iterator." -> change text
* [ ] Link "docs.rs" inline
* [ ] Change rustdoc button give info about rustdoc
* [ ] Add debugging/profiling content
* [ ] "Cargo Doc" -> "Rustdoc"

* [ ] Stretch goal: Rustfmt and Clippy should link to informative pages/web site rather than there repos, or at the very least to a specific 'getting started'/overview doc in the repo.

**Comment by thadguidry** [comment]
- [ ] Also our [Get Started page](https://www.rust-lang.org/learn/get-started) could use a [LEARN MORE ABOUT TOOLS](https://www.rust-lang.org/tools) button in this area:

![image](https://user-images.githubusercontent.com/986438/125203740-63327400-e23f-11eb-9710-0b7d726f5831.png)

So that we have a nice hyperlink to our main /tools page which is ever expanding in this issue.
