### ISSUE TITLE
Production Page tracking issue

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/www.rust-lang.org#221]
*content*

- [ ] (formerly https://github.com/rust-lang/wubwub/pull/205#issuecomment-439117384) I'd like to personally have a bit better grasp on the "Users" section (vs the full "friends" list) and what our plans are there. One nice thing with the friends page is that we had a little bit of content available on how Rust was actually used, which is a shame to lose for these logos. I know @aidanhs and I talked about keeping the "full" friends list somewhere, not sure what the current thinking is.

- [ ] (formerly https://github.com/rust-lang/wubwub/pull/205#issuecomment-439117384) At a minimum, I'd like to workshop the section title -- "Users" makes it sound like a comprehensive list. I don't have a counter-proposal just yet, but I'll mull on it.

*design*

- [ ] (formerly https://github.com/rust-lang/wubwub/pull/205#issuecomment-439117384) Also, we'll want to put some work into making the pile of logos a more uniform size (as with the current friends page).
- [x] migrate to tachyons
- [x] responsive styling pass

**Comment by XAMPPRocky** [comment]
Closing as the current status is not clear.
