### ISSUE TITLE
CLI Page tracking issue

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/www.rust-lang.org#229]
*design*

- [ ] migrate to tachyons – in progress
    - [ ] top-level heading – not started
    - [ ] `example.hbs` – not started
    - [ ] `maintainable.hbs` – not started
    - [ ] `pitch.hbs` – in progress
        - [ ] top-level heading and container
        - [x] internal sections and content
    - [ ] `production.hbs` – not started
- [ ] responsive styling pass
- [ ] syntax highlighting for code example

**Comment by skade** [comment]
Migrated to Tachyons, along with responsive styling.

Syntax highlighting is tracked here: https://github.com/rust-lang/www.rust-lang.org/issues/349
