### ISSUE TITLE
Embedded Page tracking issue

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/www.rust-lang.org#230]
*design*

- [ ] migrate to tachyons
    - [ ] top-level heading – not started
    - [ ] `get-started.hbs` – not started
    - [ ] `pitch.hbs` – not started
    - [ ] `showcase.hbs` – not started
    - [ ] `testimonials.hbs` – not started
- [ ] responsive styling pass

**Comment by jamesmunns** [comment]
Note, once https://github.com/rust-lang/rust/pull/56291 lands we should update links to the stable embedded book

**Comment by skade** [comment]
Migrated to Tachyons, along with responsive styling.
