### ISSUE TITLE
Learn Page tracking issue

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/www.rust-lang.org#232]
*design*

- [ ] migrate to tachyons
    - [ ] `index.hbs` – started, partial
        - [ ] page-level `<header>`: no
        - [ ] `#learn-begin`: partial – not top-level container, but internals are
        - [ ] `#learn-use`: partial – not top-level container, not first layer of internal containers, but further layers are
        - [ ] `#learn-master`: partial – not top-level container, but internals are
    - [ ] `get-started.hbs` – not started
- [ ] responsive styling pass

**Comment by skade** [comment]
Tachyons migration is done, as well as responsive styling.
