### ISSUE TITLE
Landing Page tracking issue

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/www.rust-lang.org#235]
*content*

- [ ] add CTAs for language values – possibly to Rust by Example, or by linking from each important point to something that elaborates or demonstrates them

*design*

- [x] migrate to tachyons
    - [x] `index.hbs`
    - [ ] panels
        - [ ] `domains.hbs` – started
            - [ ] page container and header
            - [x] subsections
        - [ ] `get-involved.hbs` – not started
        - [ ] `language-values.hbs` – started
            - [ ] page container and header
            - [x] subsections
        - [ ] `production.hbs` – not started
    - [ ] `footer.hbs` – not started
    - [x] `nav.hbs`
    - [ ] `404.hbs`
- [x] responsive styling pass
- [ ] [Rust Logo styling](https://github.com/rust-lang/new-rust-www/issues/309)

**Comment by skade** [comment]
Content: CTA are tracked here. Tachyons migration is done.

https://github.com/rust-lang/www.rust-lang.org/issues/351
